### ISSUE TITLE
Command Copy

### ISSUE THREAD

**Issue by ghost** [betomoedano/Code-With-Beto-Issues#1]
Hola Beto! 
Cuando intento copiar un script que pones en la parte de abajo del video, no se copia el texto. Por ejemplo pones un comando para correr en la terminal y cuando hago cmd + c en mac no se copia. tengo que hacer doble clik y seleccionar la opcion de copiar para que realmente se copie. No se si sea mi computadora o sea la plataforma. Lo raro es que en otras paginas si puedo hacer el cmd + c para copiar pero en la plataforma del curso no me deja.

**Comment by betomoedano** [comment]
Hey @Diegogal04!
Estaba probando tu issue en mi mac y a mi me funciona perfectamente 🤔

De cualquier forma voy a integrar un boton para copiar, algo como esto:
![Screen Shot 2022-09-19 at 4 09 53 PM](https://user-images.githubusercontent.com/43630417/191107554-fb78a531-2e02-4ce7-bd57-9b3e599c1d86.png)

Espero eso resuelva tu problema.

Saludos

**Comment by betomoedano** [comment]
Ya agregue la feature, se ve asi:
![Screen Shot 2022-09-19 at 7 00 54 PM](https://user-images.githubusercontent.com/43630417/191133981-b040e6dd-8bdb-43b3-96c4-40289bf644db.png)

Espero te sirva y con esto cierro este issue! 👍

**Comment by ghost** [comment]
Muhcas Gracias Beto!
Oye y nada mas para felicitarte, esta padrisimo el curso y me esta
encantando. Apenas llevo 30% pero esta padrisimo. Ya se lo recomende a
todos mis cuates. Mucho exito.
P.D: Me encanta el diseño de la platafomra.

[image: Email sender photo]
<https://twitter.com/Haru_mex> <https://www.instagram.com/d_galindoo/>
<https://www.linkedin.com/in/diego-galindo-0b66a217b/>
<https://www.youtube.com/channel/UCqZrSLS4l0MFOQx7aAytcAA>
Regards
Diego Galindo Gomez
Chief Executive Officer (CEO) at Haru
@ ***@***.***
W haru.com.mx
T 5538869673

**Comment by betomoedano** [comment]
Muchas gracias! Eso me motiva mucho a seguir! 😁
