### ISSUE TITLE
React with TypeScript - Missing contenet

### ISSUE THREAD

**Issue by vectorkovacspeter** [betomoedano/Code-With-Beto-Issues#12]
Hello,

the page: https://codewithbeto.dev/reactCourse/designSystem is empty :)

**Comment by vectorkovacspeter** [comment]
And also all the sections above it :(

**Comment by betomoedano** [comment]
Sorry for the confusion. As explained in the course landing page this lessons are being released as soon as we finish them, this weekend the style and design lessons will be available.
