### ISSUE TITLE
Plataforma caída

### ISSUE THREAD

**Issue by asdsoft** [betomoedano/Code-With-Beto-Issues#13]
Buenos días, la plataforma devuelve errores 404.

Gracias por arreglarla lo antes posible, necesito avanzar en el curso.

**Comment by betomoedano** [comment]
Puedes compartir screenshot?

No puedo replicar el issue. Todo funciona bien de mi parte

**Comment by asdsoft** [comment]
![Captura de pantalla 2023-11-27 a las 16 31 14](https://github.com/betomoedano/Code-With-Beto-Issues/assets/19497888/7869a89a-719f-4bf6-884f-1c68267b0f25)
![Captura de pantalla 2023-11-27 a las 16 31 43](https://github.com/betomoedano/Code-With-Beto-Issues/assets/19497888/5596d696-aca1-4a3f-940d-2c05dca9a672)

**Comment by betomoedano** [comment]
Por favor intenta de nuevo. Hice un rollback mientras que me tomo un tiempo para revisar el issue. Gracias por el reporte

**Comment by asdsoft** [comment]
Ahora perfecto, muchas gracias @betomoedano !!! 😃
