### ISSUE TITLE
I can't find the repo for https://www.youtube.com/watch?v=s542Fe7QBuM&t

### ISSUE THREAD

**Issue by reanzi** [betomoedano/Code-With-Beto-Issues#2]
Hi! I've been watching your videos lately, but this video [https://www.youtube.com/watch?v=s542Fe7QBuM&t=6s](url)  I can find the repo, there's a Component you used I want to take a look at it;  a ```headerSeactOptions```; If you don't mind you can even reply it here.
Thanks. I visited and created an account on you site, you got a lot of cool stuffs there, good work

**Comment by betomoedano** [comment]
Hey, sorry for the late replay. I believe this is the repo you are looking for [https://github.com/betomoedano/React-Navigation-Tutorial](https://github.com/betomoedano/React-Navigation-Tutorial)
