### ISSUE TITLE
"Sign Up" does not work

### ISSUE THREAD

**Issue by dev462** [betomoedano/Code-With-Beto-Issues#20]
when attempting to "Sign Up" on the website, it displays the "Sign In" pop-up and you can't actually create an account for purchasing a course.

**Comment by betomoedano** [comment]
Can you share a screenshot?

**Comment by dev462** [comment]
after looking at older issues, this was reported 4 years ago and doesn't appear to fixed. apparently using email account is not actually supported and a google account is required.

**Comment by betomoedano** [comment]
Correct! We only support sign-in with Google
