### ISSUE TITLE
No puedo acceder al curso desde mi celular

### ISSUE THREAD

**Issue by ivgomez** [betomoedano/Code-With-Beto-Issues#4]
Hola cordial saludo, acabo de realizar la compra de tu curso de react native pero tengo problemas al acceder desde mi celular debido a que me pide realizar el pago de nuevo. Agradezco tu ayuda con este issue.

**Comment by betomoedano** [comment]
Hola 👋🏼 

Estas seguro que has iniciado sesión en tu celular? Por favor verifica que estás autenticado y después trata de entrar al curso. 

Si tu problema persiste por favor agrega un Screenshot
