### ISSUE TITLE
Feature Request: Persistent Language Preference for Course Navigation

### ISSUE THREAD

**Issue by lahirudx** [betomoedano/Code-With-Beto-Issues#6]
Dear Beto,

I have noticed something that might be the default setting on your site while taking your React Native course in English. I find it slightly inconvenient that I have to manually select video language every time I switch between videos. It would significantly enhance my learning experience if there were a feature in place that could retain my language preference.

Thank you for your attention to this matter.

Best regards.

**Comment by betomoedano** [comment]
Hello Lahiru,

I hope you’re doing well, that is a great idea 💡

Thanks for your suggestion. I’ll start the implementation as soon as possible.

Best regards,
Beto

Sent from my iPhone

On Jul 1, 2023, at 12:48 PM, Lahiru Amarasooriya ***@***.***> wrote:


Dear Beto,

I have noticed something that might be the default setting on your site while taking your React Native course in English. I find it slightly inconvenient that I have to manually select video language every time I switch between videos. It would significantly enhance my learning experience if there were a feature in place that could retain my language preference.

Thank you for your attention to this matter.

Best regards.
