### ISSUE TITLE
No tengo acceso al curso que compre de react native

### ISSUE THREAD

**Issue by rolas91** [betomoedano/Code-With-Beto-Issues#7]
Buenas tardes yo compre el curso pero ahora no veo que tenga acceso al cuurso favor nnecesito ayuda para saber que esta pasando

**Comment by betomoedano** [comment]
Hola Rolando,

Por favor haz sign in con email, ya que si tratas de acceder con google te va a generar una cuenta nueva.

Avisame si esto te funciona,
Att.
Beto

On Jul 13, 2023, at 2:17 PM, Rolando Sanchez ***@***.***> wrote:



Buenas tardes yo compre el curso pero ahora no veo que tenga acceso al cuurso favor nnecesito ayuda para saber que esta pasando
