### ISSUE TITLE
Can't watch the video because of privace settings

### ISSUE THREAD

**Issue by blimatech** [betomoedano/Code-With-Beto-Issues#9]
Hello Beto,
I have watched your videos in the past and today I wanted to rewatch them but I got this error message:
![Captura de ecrã 2023-11-06 170242](https://github.com/betomoedano/Code-With-Beto-Issues/assets/48926353/944861bd-bc98-4a7c-86a5-4ad10662ff05)

**Comment by betomoedano** [comment]
Can you try reloading? I'm not able to replicate the issue

**Comment by blimatech** [comment]
Now is working. Not sure what happen, but thanks for the feedback.
